### ISSUE TITLE
Error au lancement de combat - Flo

### ISSUE THREAD

**Issue by NB0174** [NB0174/AbricotGame#20]
Traceback (most recent call last):
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/client final/main.py", line 283, in <module>
    main()
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/client final/main.py", line 279, in main
    actif = boucle(fenetre, joueur)
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/client final/main.py", line 251, in boucle
    joueur.clic()
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/client final/main.py", line 182, in clic
    self.move_to(case)
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/client final/main.py", line 189, in move_to
    del self.chemin[0]
IndexError: list assignment index out of range

**Comment by NB0174** [comment]
Apparait hors combat, si clic sur obstacle

**Comment by NB0174** [comment]
Car calculate_movement avec pour parametre end un obstacle renvoie []
et for i in range(len(self.chemin) - 1, 0, -1): cherche un indice inexistant

**Comment by leoTigers** [comment]
del self.chemin[0] or self.chemin []
Donc plutot faire 
self.chemin = []

**Comment by fg1989** [comment]
Probleme réglé
