### ISSUE TITLE
Serveur - Flo

### ISSUE THREAD

**Issue by NB0174** [NB0174/AbricotGame#28]
Traceback (most recent call last):
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/serveurfinal/main.py", line 69, in <module>
    main()
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/serveurfinal/main.py", line 65, in main
    ids, joueurs, combats = boucle(commandes, combats, ids, joueurs)
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/serveurfinal/main.py", line 51, in boucle
    i.update(combats)
  File "C:\Users\boeck\Desktop\Code\AbricotGit2\AbricotGame\serveurfinal\classesentitee.py", line 246, in update
    mobgroup.move(self, combats)
TypeError: move() takes 2 positional arguments but 3 were given

**Comment by fg1989** [comment]
Probleme réglé
