### ISSUE TITLE
Player.max_attributs - Flo

### ISSUE THREAD

**Issue by NB0174** [NB0174/AbricotGame#32]
Traceback (most recent call last):
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/serveurfinal/main.py", line 69, in <module>
    main()
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/serveurfinal/main.py", line 65, in main
    ids, joueurs, combats = boucle(commandes, combats, ids, joueurs)
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/serveurfinal/main.py", line 53, in boucle
    i.update()
  File "C:\Users\boeck\Desktop\Code\AbricotGit2\AbricotGame\serveurfinal\classesentitee.py", line 207, in update
    self.target, self.path = self.find_target()
  File "C:\Users\boeck\Desktop\Code\AbricotGit2\AbricotGame\serveurfinal\classesentitee.py", line 63, in find_target
    stats[player] *= 4 if 0 <= player.var_attributs.hp / player.max_attributs.hp < 0.25 else 3 \
ZeroDivisionError: division by zero

**Comment by fg1989** [comment]
reglé
