### ISSUE TITLE
Errur Display - Flo or Cristin

### ISSUE THREAD

**Issue by NB0174** [NB0174/AbricotGame#34]
Traceback (most recent call last):
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/client final/main.py", line 287, in <module>
    main()
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/client final/main.py", line 283, in main
    actif = boucle(fenetre, joueur)
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/client final/main.py", line 256, in boucle
    fenetre.afficher_carte(joueur)
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/client final/main.py", line 91, in afficher_carte
    self.fenetre.blit(self.textures_mobs[i[0]], decalage(i[1]))
KeyError: 'Moutonnet_de_Guerre'

**Comment by fg1989** [comment]
Il ne faut pas changer le nom des mobs
