### ISSUE TITLE
Erreur MobGroups

### ISSUE THREAD

**Issue by NB0174** [NB0174/AbricotGame#36]
Traceback (most recent call last):
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/serveurfinal/main.py", line 69, in <module>
    main()
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/serveurfinal/main.py", line 65, in main
    ids, joueurs, combats = boucle(commandes, combats, ids, joueurs)
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/serveurfinal/main.py", line 51, in boucle
    i.update()
  File "C:\Users\boeck\Desktop\Code\AbricotGit2\AbricotGame\serveurfinal\classesentitee.py", line 259, in update
    self.mobsgroups.append(Mobgroup(self))
  File "C:\Users\boeck\Desktop\Code\AbricotGit2\AbricotGame\serveurfinal\classesentitee.py", line 310, in __init__
    range(randint(2, 8))]
  File "C:\Users\boeck\Desktop\Code\AbricotGit2\AbricotGame\serveurfinal\classesentitee.py", line 309, in <listcomp>
    self.mobgroup = [MOBS.get(choice(map.mobs), randint(map.levelmin, map.levelmax), self.group_coords) for _ in
  File "C:\Users\boeck\AppData\Local\Programs\Python\Python36\lib\random.py", line 220, in randint
    return self.randrange(a, b+1)
  File "C:\Users\boeck\AppData\Local\Programs\Python\Python36\lib\random.py", line 198, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1,1, 0)

**Comment by fg1989** [comment]
Fallait pas toucher aux json.
probleme réglé.
