### ISSUE TITLE
Crash - Flo -- URGENT

### ISSUE THREAD

**Issue by fg1989** [NB0174/AbricotGame#46]
Parfois, le programme crash sans raison quand on entre en combat. Si vous réussisser a identifier la cause du bug, merci de me le signaler.

**Comment by NB0174** [comment]
Trouvé ça :
Traceback (most recent call last):
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/client/main.py", line 427, in <module>
    main()
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/client/main.py", line 423, in main
    actif = boucle(fenetre, joueur)
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/client/main.py", line 411, in boucle
    fenetre.afficher_carte(joueur)
  File "C:/Users/boeck/Desktop/Code/AbricotGit2/AbricotGame/client/main.py", line 123, in afficher_carte
    txt = f.render(i[0] + ":" + str(i[2]), 0, (255, 255, 255))
IndexError: tuple index out of range

**Comment by leoTigers** [comment]
![image](https://cloud.githubusercontent.com/assets/25849052/26082447/4846bb5e-39d0-11e7-9729-04fd8c014414.png)

**Comment by fg1989** [comment]
J'ai mis un try catch en attendant de trouver la vraie cause du bug

**Comment by NB0174** [comment]
I = ('Hiporloc', (14, 1))
et i at ind 2 out of range

**Comment by leoTigers** [comment]
Fixed, 
![image](https://cloud.githubusercontent.com/assets/25849052/26084500/d0a49c4e-39dc-11e7-8cfa-35159980dceb.png)
